name: Dispatch workflow

on: repository_dispatch

jobs:
  publish_app:
    name: Publish
    if: github.event.action == "deploy"

    strategy:
      matrix:
        os: [ 'windows-latest' ]
        dotnet: [ '3.1.201' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: Build
        path: output

    - name: Deploy Function app
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Send a message to Microsoft Teams
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
        title: ''
        summary: 'Artifact has been deployed'
        text: ''
        theme_color: ''
        sections: '[{ "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", "activityTitle": "Artifact Deployed",  "activityText": "Artifact has been deployed" }]'
        actions: '[{ "@type": "OpenUri", "name": "Go to the app", "targets": [{ "os": "default", "uri": "${{ secrets.AZURE_FUNCTIONAPP_RESOURCE_URI }}" }] }]'
