name: Dispatch workflow

on: repository_dispatch

env:
  STEP_4: 'This is step 4'

jobs:
  publish_app:
    name: Publish
    if: github.event.action == "deploy"

    runs-on: ubuntu-latest

    steps:
    - name: Step 4
      shell: bash
      run: |
        echo $STEP_4

    - name: Send a message to Microsoft Teams
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
        title: ''
        summary: 'Artifact has been deployed'
        text: ''
        theme_color: ''
        sections: '[{ "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", "activityTitle": "Artifact Deployed",  "activityText": "Artifact has been deployed" }]'
        actions: '[{ "@type": "OpenUri", "name": "Go to the app", "targets": [{ "os": "default", "uri": "${{ secrets.AZURE_FUNCTIONAPP_RESOURCE_URI }}" }] }]'
