name: Main workflow

on: push

jobs:
  build_app:
    name: Build
    strategy:
      matrix:
        os: [ 'windows-latest' ]
        dotnet: [ '3.1.201' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dotnet restore .

    - name: Build Function app
      shell: pwsh
      run: |
        dotnet build . -c Release -o ./output

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: output

    # - name: Send a message to Microsoft Teams
    #   uses: aliencube/microsoft-teams-actions@v0.8.0
    #   with:
    #     webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
    #     title: ''
    #     summary: 'Artifact is ready to deploy'
    #     text: ''
    #     theme_color: ''
    #     sections: '[{ "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", "activityTitle": "Ready to deploy",  "activityText": "Artifact is ready to deploy" }]'
    #     actions: '[{ "@type": "HttpPOST", "name": "Publish", "target": "${{ secrets.ACTION_TARGET_URI }}", "headers": [{ "name": "x-functions-key", "value": "${{ secrets.ACTION_TARGET_AUTH_KEY }}" }], "bodyContentType": "application/json", "body": "{ \"event_type\": \"deploy\", \"client_payload\": { \"artifact\": { \"name\": \"Build 2020 Demo App\" }, \"repository\": { \"owner\": \"justinyoo\", \"name\": \"build2020-eqa36\" } } }" }]'

  publish_app:
    name: Publish
    needs: build_app
    strategy:
      matrix:
        os: [ 'windows-latest' ]
        dotnet: [ '3.1.201' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: Build
        path: output

    - name: Deploy Function app
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
